//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramicData.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double InkTableSegmenterXThreshold {
            get {
                return ((double)(this["InkTableSegmenterXThreshold"]));
            }
            set {
                this["InkTableSegmenterXThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double InkTableSegmenterYThreshold {
            get {
                return ((double)(this["InkTableSegmenterYThreshold"]));
            }
            set {
                this["InkTableSegmenterYThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double InkBulletListSegmenterYThreshold {
            get {
                return ((double)(this["InkBulletListSegmenterYThreshold"]));
            }
            set {
                this["InkBulletListSegmenterYThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PanoramicDataUseBingSearch {
            get {
                return ((bool)(this["PanoramicDataUseBingSearch"]));
            }
            set {
                this["PanoramicDataUseBingSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PanoramicDataEnableKeyboardShortcuts {
            get {
                return ((bool)(this["PanoramicDataEnableKeyboardShortcuts"]));
            }
            set {
                this["PanoramicDataEnableKeyboardShortcuts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PanoramicDataEnableCalculatedFields {
            get {
                return ((bool)(this["PanoramicDataEnableCalculatedFields"]));
            }
            set {
                this["PanoramicDataEnableCalculatedFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PanoramicDataEnableStable {
            get {
                return ((bool)(this["PanoramicDataEnableStable"]));
            }
            set {
                this["PanoramicDataEnableStable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.8")]
        public double PanoramicDataStableScaleFactor {
            get {
                return ((double)(this["PanoramicDataStableScaleFactor"]));
            }
            set {
                this["PanoramicDataStableScaleFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double PanoramicDataStableLabelFontSize {
            get {
                return ((double)(this["PanoramicDataStableLabelFontSize"]));
            }
            set {
                this["PanoramicDataStableLabelFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("titanic,tip,acm,coffee,nfl,nba")]
        public string PanoramicDataAccesibleSchemas {
            get {
                return ((string)(this["PanoramicDataAccesibleSchemas"]));
            }
            set {
                this["PanoramicDataAccesibleSchemas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PanoramicDataEnableBluetooth {
            get {
                return ((bool)(this["PanoramicDataEnableBluetooth"]));
            }
            set {
                this["PanoramicDataEnableBluetooth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PanoramicDataEnableInkingCommands {
            get {
                return ((bool)(this["PanoramicDataEnableInkingCommands"]));
            }
            set {
                this["PanoramicDataEnableInkingCommands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000000")]
        public double PanoramicDataMaxPlotItems {
            get {
                return ((double)(this["PanoramicDataMaxPlotItems"]));
            }
            set {
                this["PanoramicDataMaxPlotItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PanoramicDataIsMultiSamplingEnabled {
            get {
                return ((bool)(this["PanoramicDataIsMultiSamplingEnabled"]));
            }
            set {
                this["PanoramicDataIsMultiSamplingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableKeyboardMultitouchSimulator {
            get {
                return ((bool)(this["EnableKeyboardMultitouchSimulator"]));
            }
            set {
                this["EnableKeyboardMultitouchSimulator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RenderFingers {
            get {
                return ((bool)(this["RenderFingers"]));
            }
            set {
                this["RenderFingers"] = value;
            }
        }
    }
}
