//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TitanicPopulator.BingMapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/geocode/contracts", ConfigurationName="BingMapService.IGeocodeService")]
    public interface IGeocodeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
            "ode", ReplyAction="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
            "odeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MapApi.BingMapService.ResponseSummary), Action="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
            "odeResponseSummaryFault", Name="ResponseSummary", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
        MapApi.BingMapService.GeocodeResponse Geocode(MapApi.BingMapService.GeocodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
            "ode", ReplyAction="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
            "odeResponse")]
        System.Threading.Tasks.Task<MapApi.BingMapService.GeocodeResponse> GeocodeAsync(MapApi.BingMapService.GeocodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
            "rseGeocode", ReplyAction="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
            "rseGeocodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MapApi.BingMapService.ResponseSummary), Action="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
            "rseGeocodeResponseSummaryFault", Name="ResponseSummary", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MapApi.BingMapService.GeocodeLocation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MapApi.BingMapService.UserLocation))]
        MapApi.BingMapService.GeocodeResponse ReverseGeocode(MapApi.BingMapService.ReverseGeocodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
            "rseGeocode", ReplyAction="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
            "rseGeocodeResponse")]
        System.Threading.Tasks.Task<MapApi.BingMapService.GeocodeResponse> ReverseGeocodeAsync(MapApi.BingMapService.ReverseGeocodeRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeocodeServiceChannel : TitanicPopulator.BingMapService.IGeocodeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeocodeServiceClient : System.ServiceModel.ClientBase<TitanicPopulator.BingMapService.IGeocodeService>, TitanicPopulator.BingMapService.IGeocodeService {
        
        public GeocodeServiceClient() {
        }
        
        public GeocodeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeocodeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeocodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeocodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MapApi.BingMapService.GeocodeResponse Geocode(MapApi.BingMapService.GeocodeRequest request) {
            return base.Channel.Geocode(request);
        }
        
        public System.Threading.Tasks.Task<MapApi.BingMapService.GeocodeResponse> GeocodeAsync(MapApi.BingMapService.GeocodeRequest request) {
            return base.Channel.GeocodeAsync(request);
        }
        
        public MapApi.BingMapService.GeocodeResponse ReverseGeocode(MapApi.BingMapService.ReverseGeocodeRequest request) {
            return base.Channel.ReverseGeocode(request);
        }
        
        public System.Threading.Tasks.Task<MapApi.BingMapService.GeocodeResponse> ReverseGeocodeAsync(MapApi.BingMapService.ReverseGeocodeRequest request) {
            return base.Channel.ReverseGeocodeAsync(request);
        }
    }
}
