//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShapeRecognizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShapeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShapeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShapeRecognizer.ShapeResources", typeof(ShapeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;circle&quot; NumPts=&quot;302&quot; Millseconds=&quot;3010&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Wednesday, September 07, 2011&quot; TimeOfDay=&quot;4:57:42 PM&quot;&gt;
        ///  &lt;Point X=&quot;183&quot; Y=&quot;19&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;183&quot; Y=&quot;19&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;183&quot; Y=&quot;19&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;183&quot; Y=&quot;19&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;183&quot; Y=&quot;19&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;183&quot; Y=&quot;19&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;183&quot; Y=&quot;19&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;183&quot; Y=&quot;19&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X=&quot;183 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string circle {
            get {
                return ResourceManager.GetString("circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;parallelogram&quot; NumPts=&quot;257&quot; Millseconds=&quot;2560&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;1:03:21 AM&quot;&gt;
        ///  &lt;Point X=&quot;186&quot; Y=&quot;10&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;184&quot; Y=&quot;13&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;182&quot; Y=&quot;15&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;181&quot; Y=&quot;17&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;179&quot; Y=&quot;19&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;177&quot; Y=&quot;21&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;175&quot; Y=&quot;24&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;172&quot; Y=&quot;27&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string parallelogram {
            get {
                return ResourceManager.GetString("parallelogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;parallelogram_1&quot; NumPts=&quot;246&quot; Millseconds=&quot;2450&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;1:04:00 AM&quot;&gt;
        ///  &lt;Point X=&quot;90&quot; Y=&quot;203&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;90&quot; Y=&quot;203&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;90&quot; Y=&quot;203&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;90&quot; Y=&quot;202&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;90&quot; Y=&quot;202&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;91&quot; Y=&quot;202&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;91&quot; Y=&quot;202&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;92&quot; Y=&quot;202&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string parallelogram_1 {
            get {
                return ResourceManager.GetString("parallelogram_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;parallelogram_2&quot; NumPts=&quot;251&quot; Millseconds=&quot;2500&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;1:04:34 AM&quot;&gt;
        ///  &lt;Point X=&quot;151&quot; Y=&quot;209&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;151&quot; Y=&quot;208&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;152&quot; Y=&quot;208&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;152&quot; Y=&quot;207&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;153&quot; Y=&quot;206&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;154&quot; Y=&quot;205&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;155&quot; Y=&quot;203&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;157&quot; Y=&quot;201&quot; T=&quot;70&quot; /&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string parallelogram_2 {
            get {
                return ResourceManager.GetString("parallelogram_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;parallelogram_3&quot; NumPts=&quot;252&quot; Millseconds=&quot;2510&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;1:05:08 AM&quot;&gt;
        ///  &lt;Point X=&quot;278&quot; Y=&quot;23&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;275&quot; Y=&quot;23&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;274&quot; Y=&quot;23&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;272&quot; Y=&quot;23&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;270&quot; Y=&quot;23&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;268&quot; Y=&quot;23&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;266&quot; Y=&quot;24&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;264&quot; Y=&quot;24&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string parallelogram_3 {
            get {
                return ResourceManager.GetString("parallelogram_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;parallelogram_4&quot; NumPts=&quot;366&quot; Millseconds=&quot;3650&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;1:08:30 AM&quot;&gt;
        ///  &lt;Point X=&quot;147&quot; Y=&quot;10&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;144&quot; Y=&quot;14&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;142&quot; Y=&quot;16&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;140&quot; Y=&quot;19&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;139&quot; Y=&quot;21&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;137&quot; Y=&quot;24&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;135&quot; Y=&quot;27&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;133&quot; Y=&quot;29&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string parallelogram_4 {
            get {
                return ResourceManager.GetString("parallelogram_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;parallelogramR_5&quot; NumPts=&quot;233&quot; Millseconds=&quot;2320&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;1:20:53 AM&quot;&gt;
        ///  &lt;Point X=&quot;59&quot; Y=&quot;27&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;61&quot; Y=&quot;32&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;62&quot; Y=&quot;36&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;63&quot; Y=&quot;39&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;64&quot; Y=&quot;44&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;66&quot; Y=&quot;49&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;67&quot; Y=&quot;54&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;69&quot; Y=&quot;60&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X=&quot;71&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string parallelogramR_5 {
            get {
                return ResourceManager.GetString("parallelogramR_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;parallelogramR_6&quot; NumPts=&quot;259&quot; Millseconds=&quot;2580&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;1:21:10 AM&quot;&gt;
        ///  &lt;Point X=&quot;137&quot; Y=&quot;208&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;137&quot; Y=&quot;208&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;137&quot; Y=&quot;208&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;137&quot; Y=&quot;208&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;137&quot; Y=&quot;208&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;138&quot; Y=&quot;207&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;139&quot; Y=&quot;207&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;139&quot; Y=&quot;207&quot; T=&quot;70&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string parallelogramR_6 {
            get {
                return ResourceManager.GetString("parallelogramR_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;parallelogramR_7&quot; NumPts=&quot;264&quot; Millseconds=&quot;2630&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;1:21:45 AM&quot;&gt;
        ///  &lt;Point X=&quot;261&quot; Y=&quot;223&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;261&quot; Y=&quot;223&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;261&quot; Y=&quot;223&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;261&quot; Y=&quot;223&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;261&quot; Y=&quot;223&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;260&quot; Y=&quot;223&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;260&quot; Y=&quot;223&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;259&quot; Y=&quot;222&quot; T=&quot;70&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string parallelogramR_7 {
            get {
                return ResourceManager.GetString("parallelogramR_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;parallelogramR_8&quot; NumPts=&quot;246&quot; Millseconds=&quot;2450&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;1:22:43 AM&quot;&gt;
        ///  &lt;Point X=&quot;126&quot; Y=&quot;42&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;125&quot; Y=&quot;42&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;124&quot; Y=&quot;42&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;124&quot; Y=&quot;42&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;123&quot; Y=&quot;42&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;122&quot; Y=&quot;42&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;121&quot; Y=&quot;42&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;119&quot; Y=&quot;42&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string parallelogramR_8 {
            get {
                return ResourceManager.GetString("parallelogramR_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;parallelogramR_9&quot; NumPts=&quot;315&quot; Millseconds=&quot;3140&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;8:27:48 AM&quot;&gt;
        ///  &lt;Point X=&quot;159&quot; Y=&quot;8&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;159&quot; Y=&quot;8&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;159&quot; Y=&quot;8&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;159&quot; Y=&quot;8&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;159&quot; Y=&quot;8&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;159&quot; Y=&quot;8&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;159&quot; Y=&quot;8&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;159&quot; Y=&quot;8&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X=&quot;159&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string parallelogramR_9 {
            get {
                return ResourceManager.GetString("parallelogramR_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;rect_1&quot; NumPts=&quot;367&quot; Millseconds=&quot;3660&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Wednesday, September 07, 2011&quot; TimeOfDay=&quot;9:42:55 AM&quot;&gt;
        ///  &lt;Point X=&quot;105&quot; Y=&quot;71&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;105&quot; Y=&quot;71&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;105&quot; Y=&quot;71&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;105&quot; Y=&quot;71&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;105&quot; Y=&quot;71&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;105&quot; Y=&quot;71&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;105&quot; Y=&quot;71&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;105&quot; Y=&quot;71&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X=&quot;105 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rect_1 {
            get {
                return ResourceManager.GetString("rect_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;rect_2&quot; NumPts=&quot;797&quot; Millseconds=&quot;7960&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Wednesday, September 07, 2011&quot; TimeOfDay=&quot;9:44:07 AM&quot;&gt;
        ///  &lt;Point X=&quot;93&quot; Y=&quot;4&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;93&quot; Y=&quot;4&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;93&quot; Y=&quot;4&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;93&quot; Y=&quot;4&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;93&quot; Y=&quot;4&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;93&quot; Y=&quot;4&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;93&quot; Y=&quot;4&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;93&quot; Y=&quot;4&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X=&quot;93&quot; Y=&quot;4&quot; T=&quot;80&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rect_2 {
            get {
                return ResourceManager.GetString("rect_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;rect_3&quot; NumPts=&quot;247&quot; Millseconds=&quot;2460&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Saturday, September 10, 2011&quot; TimeOfDay=&quot;11:58:03 PM&quot;&gt;
        ///  &lt;Point X=&quot;24&quot; Y=&quot;63&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;24&quot; Y=&quot;63&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;24&quot; Y=&quot;63&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;24&quot; Y=&quot;63&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;24&quot; Y=&quot;63&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;24&quot; Y=&quot;64&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;24&quot; Y=&quot;64&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;24&quot; Y=&quot;65&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X=&quot;25&quot; Y=&quot;67&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rect_3 {
            get {
                return ResourceManager.GetString("rect_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;rect_4&quot; NumPts=&quot;947&quot; Millseconds=&quot;9460&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Thursday, September 08, 2011&quot; TimeOfDay=&quot;2:43:52 PM&quot;&gt;
        ///  &lt;Point X=&quot;72&quot; Y=&quot;83&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;72&quot; Y=&quot;83&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;72&quot; Y=&quot;83&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;72&quot; Y=&quot;83&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;72&quot; Y=&quot;83&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;72&quot; Y=&quot;83&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;72&quot; Y=&quot;83&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;72&quot; Y=&quot;83&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X=&quot;72&quot; Y=&quot;83&quot; T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rect_4 {
            get {
                return ResourceManager.GetString("rect_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;rightTriangle&quot; NumPts=&quot;389&quot; Millseconds=&quot;3880&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Wednesday, September 07, 2011&quot; TimeOfDay=&quot;9:45:41 AM&quot;&gt;
        ///  &lt;Point X=&quot;77&quot; Y=&quot;39&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;77&quot; Y=&quot;39&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;77&quot; Y=&quot;39&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;77&quot; Y=&quot;39&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;77&quot; Y=&quot;39&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;77&quot; Y=&quot;39&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;77&quot; Y=&quot;39&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;77&quot; Y=&quot;39&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X=&quot;77&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rightTriangle {
            get {
                return ResourceManager.GetString("rightTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;trapezoid&quot; NumPts=&quot;824&quot; Millseconds=&quot;8230&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Wednesday, September 07, 2011&quot; TimeOfDay=&quot;4:50:24 PM&quot;&gt;
        ///  &lt;Point X=&quot;142&quot; Y=&quot;8&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;142&quot; Y=&quot;8&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;142&quot; Y=&quot;8&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;142&quot; Y=&quot;8&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;142&quot; Y=&quot;8&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;142&quot; Y=&quot;8&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;142&quot; Y=&quot;8&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;142&quot; Y=&quot;8&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X=&quot;142&quot; Y=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trapezoid {
            get {
                return ResourceManager.GetString("trapezoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;trapezoid_2&quot; NumPts=&quot;273&quot; Millseconds=&quot;2720&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;12:17:42 AM&quot;&gt;
        ///  &lt;Point X=&quot;219&quot; Y=&quot;32&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;219&quot; Y=&quot;32&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;218&quot; Y=&quot;31&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;218&quot; Y=&quot;31&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;218&quot; Y=&quot;31&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;218&quot; Y=&quot;31&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;218&quot; Y=&quot;31&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;217&quot; Y=&quot;31&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trapezoid_2 {
            get {
                return ResourceManager.GetString("trapezoid_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;trapezoid_3&quot; NumPts=&quot;956&quot; Millseconds=&quot;9550&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Wednesday, September 07, 2011&quot; TimeOfDay=&quot;4:51:43 PM&quot;&gt;
        ///  &lt;Point X=&quot;50&quot; Y=&quot;183&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;50&quot; Y=&quot;183&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;50&quot; Y=&quot;183&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;50&quot; Y=&quot;183&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;50&quot; Y=&quot;183&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;50&quot; Y=&quot;183&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;50&quot; Y=&quot;183&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;50&quot; Y=&quot;183&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trapezoid_3 {
            get {
                return ResourceManager.GetString("trapezoid_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;trapezoid_4&quot; NumPts=&quot;272&quot; Millseconds=&quot;2710&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;12:59:10 AM&quot;&gt;
        ///  &lt;Point X=&quot;312&quot; Y=&quot;193&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;311&quot; Y=&quot;192&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;311&quot; Y=&quot;192&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;310&quot; Y=&quot;192&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;309&quot; Y=&quot;192&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;309&quot; Y=&quot;192&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;308&quot; Y=&quot;192&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;307&quot; Y=&quot;192&quot; T=&quot;70&quot; /&gt;
        ///  &lt;P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trapezoid_4 {
            get {
                return ResourceManager.GetString("trapezoid_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;triangle&quot; NumPts=&quot;170&quot; Millseconds=&quot;1690&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;12:52:00 AM&quot;&gt;
        ///  &lt;Point X=&quot;100&quot; Y=&quot;199&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;100&quot; Y=&quot;199&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;100&quot; Y=&quot;199&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;100&quot; Y=&quot;199&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;100&quot; Y=&quot;199&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;101&quot; Y=&quot;198&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;101&quot; Y=&quot;198&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;101&quot; Y=&quot;197&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Poin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string triangle {
            get {
                return ResourceManager.GetString("triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;triangle_1&quot; NumPts=&quot;427&quot; Millseconds=&quot;4260&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Wednesday, September 07, 2011&quot; TimeOfDay=&quot;9:44:59 AM&quot;&gt;
        ///  &lt;Point X=&quot;122&quot; Y=&quot;99&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;122&quot; Y=&quot;99&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;122&quot; Y=&quot;99&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;122&quot; Y=&quot;99&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;122&quot; Y=&quot;99&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;122&quot; Y=&quot;99&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;122&quot; Y=&quot;99&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;122&quot; Y=&quot;99&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Point X= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string triangle_1 {
            get {
                return ResourceManager.GetString("triangle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Gesture Name=&quot;triangle_2&quot; NumPts=&quot;140&quot; Millseconds=&quot;1390&quot; AppName=&quot;DollarRecognizer&quot; AppVer=&quot;1.0.0.0&quot; Date=&quot;Sunday, September 11, 2011&quot; TimeOfDay=&quot;12:54:43 AM&quot;&gt;
        ///  &lt;Point X=&quot;210&quot; Y=&quot;199&quot; T=&quot;0&quot; /&gt;
        ///  &lt;Point X=&quot;210&quot; Y=&quot;199&quot; T=&quot;10&quot; /&gt;
        ///  &lt;Point X=&quot;210&quot; Y=&quot;199&quot; T=&quot;20&quot; /&gt;
        ///  &lt;Point X=&quot;210&quot; Y=&quot;199&quot; T=&quot;30&quot; /&gt;
        ///  &lt;Point X=&quot;210&quot; Y=&quot;199&quot; T=&quot;40&quot; /&gt;
        ///  &lt;Point X=&quot;210&quot; Y=&quot;199&quot; T=&quot;50&quot; /&gt;
        ///  &lt;Point X=&quot;210&quot; Y=&quot;199&quot; T=&quot;60&quot; /&gt;
        ///  &lt;Point X=&quot;210&quot; Y=&quot;199&quot; T=&quot;70&quot; /&gt;
        ///  &lt;Po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string triangle_2 {
            get {
                return ResourceManager.GetString("triangle_2", resourceCulture);
            }
        }
    }
}
