//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramicDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldAlias
    {
        public int Id { get; set; }
        public int Priority { get; set; }
        public string Alias { get; set; }
        private int field_id { get; set; }
    
        public virtual FieldInfo FieldInfo { get; set; }
    }
}
