//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramicDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldInfo
    {
        public FieldInfo()
        {
            this.FieldAliases = new HashSet<FieldAlias>();
            this.FromTableDependencies = new HashSet<TableDependency>();
            this.ToTableDependencies = new HashSet<TableDependency>();
            this.PrimaryKeyTableInfos = new HashSet<TableInfo>();
            this.table_info1 = new HashSet<TableInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Visible { get; set; }
        public string DataType { get; set; }
        private int table_id { get; set; }
        public string VisualizationType { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> BinSize { get; set; }
    
        public virtual ICollection<FieldAlias> FieldAliases { get; set; }
        public virtual TableInfo TableInfo { get; set; }
        public virtual ICollection<TableDependency> FromTableDependencies { get; set; }
        public virtual ICollection<TableDependency> ToTableDependencies { get; set; }
        public virtual ICollection<TableInfo> PrimaryKeyTableInfos { get; set; }
        public virtual ICollection<TableInfo> table_info1 { get; set; }
    }
}
