//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramicDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class panoramicdataEntities : DbContext
    {
        public panoramicdataEntities()
            : base("name=panoramicdataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FieldAlias> FieldAlias { get; set; }
        public DbSet<FieldInfo> FieldInfoes { get; set; }
        public DbSet<TableAlias> TableAlias { get; set; }
        public DbSet<TableDependency> TableDependencies { get; set; }
        public DbSet<TableInfo> TableInfoes { get; set; }
    }
}
