//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramicDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDependency
    {
        public int Id { get; set; }
        private int from_table_id { get; set; }
        private int to_table_id { get; set; }
        private int from_field_id { get; set; }
        private int to_field_id { get; set; }
        public string Cardinality { get; set; }
        public string RelationshipName { get; set; }
    
        public virtual FieldInfo FromFieldInfo { get; set; }
        public virtual FieldInfo ToFieldInfo { get; set; }
        public virtual TableInfo FromTableInfo { get; set; }
        public virtual TableInfo ToTableInfo { get; set; }
    }
}
