//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramicDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableInfo
    {
        public TableInfo()
        {
            this.FieldInfos = new HashSet<FieldInfo>();
            this.TableAliases = new HashSet<TableAlias>();
            this.FromTableDependencies = new HashSet<TableDependency>();
            this.ToTableDependencies = new HashSet<TableDependency>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        private int pk_field_info { get; set; }
        public string SchemaName { get; set; }
        private Nullable<int> identifier_field_id { get; set; }
    
        public virtual ICollection<FieldInfo> FieldInfos { get; set; }
        public virtual ICollection<TableAlias> TableAliases { get; set; }
        public virtual ICollection<TableDependency> FromTableDependencies { get; set; }
        public virtual ICollection<TableDependency> ToTableDependencies { get; set; }
        public virtual FieldInfo PrimaryKeyFieldInfo { get; set; }
        public virtual FieldInfo IdentifierFieldInfo { get; set; }
    }
}
